# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           regreet
Version:        0.2.0
Release:        %autorelease
Summary:        Clean and customizable greeter for greetd
URL:            https://github.com/rharish101/ReGreet
License:        GPL-3.0-or-later
Source0:        %{url}/archive/refs/tags/%{version}.tar.gz
Source1:        %{name}-0.2.0-vendor.tar.xz
BuildRequires:  cargo-rpm-macros systemd-rpm-macros
BuildRequires:  pkgconfig(gtk4) pkgconfig(libadwaita-1) pkgconfig(libseccomp) pkgconfig(lcms2)
Requires(post): systemd
Requires:       greetd

%global _description %{expand:
Clean and customizable greeter for greetd.}

%description
A clean and customizable GTK-based greetd greeter written in Rust using Relm4. This is meant to be run under a Wayland compositor (like Sway).

%prep
%autosetup -n ReGreet-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
install -Dpm0644 systemd-tmpfiles.conf %{buildroot}%{_tmpfilesdir}/%{name}.conf
install -Dpm0644 %{name}.sample.toml %{buildroot}%{_docdir}/%{name}/%{name}.sample.toml

%post
%tmpfiles_create %{_tmpfilesdir}/%{name}.conf

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSES/GPL-3.0-or-later.txt
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc %{_docdir}/%{name}/%{name}.sample.toml
%{_tmpfilesdir}/%{name}.conf
%{_bindir}/%{name}

%changelog
%autochangelog
